-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    COUNT(DISTINCT USER_ID) AS PUCHASED_USERS, 
    ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*)
                                FROM USER_INFO 
                                WHERE JOINED >= '2021-01-01 00:00:00' 
                                    AND JOINED < '2022-01-01 00:00:00'), 1) PUCHASED_RATIO
FROM USER_INFO T1 JOIN ONLINE_SALE T2 USING(USER_ID)
WHERE JOINED LIKE '2021%'
GROUP BY MONTH(SALES_DATE)
ORDER BY YEAR, MONTH;