-- 코드를 입력하세요
SELECT ANIMAL_ID, T1.ANIMAL_TYPE, T1.NAME
FROM ANIMAL_INS T1 JOIN ANIMAL_OUTS T2 USING(ANIMAL_ID)
WHERE SEX_UPON_INTAKE LIKE 'Intact%'
    AND SEX_UPON_OUTCOME IN ('Spayed Female', 'Neutered Male')
ORDER BY ANIMAL_ID