-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, 
    CONCAT_WS(" ", T2.CITY, T2.STREET_ADDRESS1, T2.STREET_ADDRESS2) AS '전체주소',
    CONCAT_WS("-", SUBSTRING(T2.TLNO, 1, 3), SUBSTR(T2.TLNO, 4, 4), RIGHT(T2.TLNO, 4)) AS '전화번호'
FROM USED_GOODS_BOARD T1 JOIN USED_GOODS_USER T2 ON T1.WRITER_ID = T2.USER_ID
GROUP BY WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY USER_ID DESC;