-- 코드를 입력하세요
SELECT TITLE, BOARD_ID, REPLY_ID, USED_GOODS_REPLY.WRITER_ID, USED_GOODS_REPLY.CONTENTS, DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD JOIN USED_GOODS_REPLY USING(BOARD_ID)
WHERE USED_GOODS_BOARD.CREATED_DATE LIKE '2022-10-%'
ORDER BY USED_GOODS_REPLY.CREATED_DATE, TITLE;