-- 코드를 입력하세요
SELECT A.APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, A.APNT_YMD
FROM APPOINTMENT A JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID JOIN PATIENT P USING(PT_NO)
WHERE APNT_YMD LIKE '2022-04-13%'
    AND A.MCDP_CD = 'CS'
    AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;